# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ns3-http-transfer-example', ['dash', 'internet', 'wifi', 'buildings', 'dash-streaming', 'point-to-point'])
    obj.source = 'ns3-http-transfer-example1.cc'
